import Head from "next/head";
import { useEffect } from "react";
import Stories from "@/components/Stories";
import Feed from "@/components/Feed";
import Post from "@/components/Post";
import { useSession } from "next-auth/react";
import { useRouter } from "next/router";
import Model from "@/components/Model";

export default function Home({setProgress}) {
  const {data:session,status} = useSession();
  const router = useRouter()
  useEffect(() => {
    if(!session || status === "unauthenticated"){
      router.push("/auth/signin")
    }
    setProgress(30)
    setProgress(100)
  }, [])
  return (
    <>
      <Head>
        <title>Photogram-Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     {session && <Model />}

     {session && <div className="p-2 sm:p-4 lg:ml-64 sm:ml-16 sm:flex">
        <div className="w-full sm:w-3/5">
          <div className="sm:mx-2 md:mx-10">
            <Stories />
          </div>
          <Post />
        </div>
     { session && <div className="hidden w-2/5 sm:block">
          <Feed />
        </div>}
        <div>
        </div>
      </div>}
    </>
  );
}
